language: python
sudo: false
branches:
  only:
    - master
python:
  - 3.5
  - 3.6

env:
  - PYSAL_PYPI=true #testing on dependencies libpysal, esda, mapcalssify on pypi
  - PYSAL_PYPI=false

matrix:
  allow_failures:
      - python: 3.5
        env: PYSAL_PYPI=false
      - python: 3.6
        env: PYSAL_PYPI=false

before_install:
  - wget https://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b -p ./miniconda
  - export PATH=`pwd`/miniconda/bin:$PATH
  - conda update --yes conda
  - conda create -y -q -n test-env python=$TRAVIS_PYTHON_VERSION
  - source activate test-env

install:
  - conda install --yes pip
  - pip install -r requirements.txt
  - pip install -r requirements_tests.txt
  - pip install https://github.com/pysal/splot/archive/master.zip
  - if "$PYSAL_PYPI"; then
        echo 'testing pypi libpysal esda mapclassify';
    else
        echo 'testing git libpysal esda mapclassify';
        git clone https://github.com/pysal/libpysal.git; cd libpysal; pip install .; cd ../;
        git clone https://github.com/pysal/mapclassify.git; cd mapclassify; pip install .; cd ../;
        git clone https://github.com/pysal/esda.git; cd esda; pip install .; cd ../;
    fi;
  # We need the Agg backend to use Matplotlib on TravisCI, otherwise
  # we get an error "DISPLAY variable not set"
  - cp testing/matplotlibrc .


script:
  - python setup.py sdist >/dev/null
  - python setup.py install
  - nosetests --verbose --with-coverage --cover-package=giddy
#  - nosetests --verbose giddy;

notifications:
    email:
        recipients:
            - weikang9009@gmail.com
            - sjsrey@gmail.com
            - levi.john.wolf@gmail.com
        on_success: change
        on_failure: always
after_success:
  - coveralls