language: python
dist: xenial
sudo: true
branches:
  only:
    - master
python:
  - 3.6
  - 3.7

env:
  - PYSAL_PYPI=true #testing on dependencies libpysal, esda, mapcalssify on pypi
  - PYSAL_PYPI=false

matrix:
  allow_failures:
      - python: 3.6
        env: PYSAL_PYPI=false
      - python: 3.7
        env: PYSAL_PYPI=false

before_install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b -p ./miniconda
  - export PATH=`pwd`/miniconda/bin:$PATH
  - conda update --yes conda
  - conda config --add channels conda-forge --force
  - conda config --set channel_priority strict
  - conda config --set safety_checks disabled
  - conda create -y --name test-env python=$TRAVIS_PYTHON_VERSION --file requirements.txt --file requirements_tests.txt
  - source activate test-env

install:
  - conda install --yes pip
  #assuming pypi and conda-forge are hosting the same release
  - if "$PYSAL_PYPI"; then
        echo 'testing pypi libpysal esda mapclassify splot';
    else
        echo 'testing git libpysal esda mapclassify splot';
        git clone https://github.com/pysal/splot.git; cd splot; pip install .; cd ../;
        git clone https://github.com/pysal/libpysal.git; cd libpysal; pip install .; cd ../;
        git clone https://github.com/pysal/mapclassify.git; cd mapclassify; pip install .; cd ../;
        git clone https://github.com/pysal/esda.git; cd esda; pip install .; cd ../;
    fi;
  # We need the Agg backend to use Matplotlib on TravisCI, otherwise
  # we get an error "DISPLAY variable not set"
  - cp testing/matplotlibrc .


script:
  - python setup.py sdist >/dev/null
  - python setup.py install
  - nosetests --verbose --with-doctest --with-coverage --cover-package=giddy
#  - nosetests --verbose giddy;

notifications:
    email:
        recipients:
            - weikang9009@gmail.com
            - sjsrey@gmail.com
            - levi.john.wolf@gmail.com
        on_success: change
        on_failure: always

after_success:
  - coveralls
